### ISSUE TITLE
KeyError: 'modules'

### ISSUE THREAD

**Issue by ghost** [rodjun/python_csgo_radar#6]
When running, I get error message KeyError: 'modules' on line 30 
`if self.process.get_module_size("client.dll") != offsets["modules"]["client.dll"]["size"]:`

Thank you

**Comment by TobiasHG** [comment]
i get the excact same error

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
hwnd: 1576466
pid: c_long(16036)
1732
Traceback (most recent call last):
  File "C:\Users\Bruger\Downloads\python_csgo_radar-master\python_csgo_radar-master\csgo_hack_pygame.py", line 124, in <module>
    not_a_hack = CSGORadar()
  File "C:\Users\Bruger\Downloads\python_csgo_radar-master\python_csgo_radar-master\csgo_hack_pygame.py", line 30, in __init__
    if self.process.get_module_size("client.dll") != offsets["modules"]["client.dll"]["size"]:
KeyError: 'modules'
